// <auto-generated />
namespace MVC.Labs.Day2.EmployeeForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createDBtoLocal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createDBtoLocal));
        
        string IMigrationMetadata.Id
        {
            get { return "202005091900362_createDBtoLocal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
